# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/teeramoo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/teeramoo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teeramoo/Desktop/Thesis_work/Point_cloud_segmentation/cloudVisualizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teeramoo/Desktop/Thesis_work/Point_cloud_segmentation/cloudVisualizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/teeramoo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/teeramoo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teeramoo/Desktop/Thesis_work/Point_cloud_segmentation/cloudVisualizer/CMakeFiles /home/teeramoo/Desktop/Thesis_work/Point_cloud_segmentation/cloudVisualizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teeramoo/Desktop/Thesis_work/Point_cloud_segmentation/cloudVisualizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cloudScaling

# Build rule for target.
cloudScaling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cloudScaling
.PHONY : cloudScaling

# fast build rule for target.
cloudScaling/fast:
	$(MAKE) -f CMakeFiles/cloudScaling.dir/build.make CMakeFiles/cloudScaling.dir/build
.PHONY : cloudScaling/fast

cloudScaling.o: cloudScaling.cpp.o

.PHONY : cloudScaling.o

# target to build an object file
cloudScaling.cpp.o:
	$(MAKE) -f CMakeFiles/cloudScaling.dir/build.make CMakeFiles/cloudScaling.dir/cloudScaling.cpp.o
.PHONY : cloudScaling.cpp.o

cloudScaling.i: cloudScaling.cpp.i

.PHONY : cloudScaling.i

# target to preprocess a source file
cloudScaling.cpp.i:
	$(MAKE) -f CMakeFiles/cloudScaling.dir/build.make CMakeFiles/cloudScaling.dir/cloudScaling.cpp.i
.PHONY : cloudScaling.cpp.i

cloudScaling.s: cloudScaling.cpp.s

.PHONY : cloudScaling.s

# target to generate assembly for a file
cloudScaling.cpp.s:
	$(MAKE) -f CMakeFiles/cloudScaling.dir/build.make CMakeFiles/cloudScaling.dir/cloudScaling.cpp.s
.PHONY : cloudScaling.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cloudScaling"
	@echo "... cloudScaling.o"
	@echo "... cloudScaling.i"
	@echo "... cloudScaling.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

